name: Deploy to OpenShift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to OpenShift
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install OpenShift CLI
        run: |
          curl -sL https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar xz
          sudo mv oc kubectl /usr/local/bin/
          oc version

      - name: Login to OpenShift
        run: |
          oc login --server=${{ secrets.OPENSHIFT_SERVER }} \
                  --token=${{ secrets.OPENSHIFT_TOKEN }} \
                  --insecure-skip-tls-verify=true
